version: '3.8'
services:
  go_coder:
    container_name: go-coder
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/code
    ports:
      - "3003:3003"
    tty: true

  py_coder:
    container_name: py-coder
    build:
      context: .
      dockerfile: ./Dockerfile_py
    volumes:
      - ./:/code
    ports:
      - "8008:8008"
    tty: true