version: '3.8'
services:
  go_coder:
    container_name: go-coder
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/code
    ports:
      - "3000:3000"
    tty: true

  py_coder:
    container_name: py-coder
    build:
      context: .
      dockerfile: ./Dockerfile_py
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    tty: true